
mysql:
  ip: 47.108.132.109
  port: 3306
  db: childcare
  username: root
  password: 123456

redis:
  host: 47.108.132.109
  port: 6379
  password: 123456

rocketmq:
  name-server: 47.108.132.109:9876
  access-key:
  secret-key:

minio:
  endpoint: http://47.108.132.109:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: default