
mysql:
  ip: 127.0.0.1
  port: 3306
  db: childcare
  username: root
  password: 123456

redis:
  host: 47.109.155.184
  port: 6379
  password: 123456

rocketmq:
  name-server: 47.109.155.184:9876
  access-key:
  secret-key:

minio:
  endpoint: http://47.109.155.184:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: default