spring:
  application:
    name: childCare
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO   # 集群下自动生成 ID

  redis:
    port: ${redis.port}
    host: ${redis.host}
    database: 0
    password: ${redis.password}

  datasource:
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-handlers-package: com.cqut.childcare.common.handler # 注册自定义handler

rocketmq:
  name-server: ${rocketmq.name-server}
  producer:
    group: childcareGroup
    access-key: ${rocketmq.access-key}
    secret-key: ${rocketmq.secret-key}
knife4j:
  enable: true

childcare:
  jwt:
    secret: 123456









